# Generated by Django 5.2.1 on 2025-05-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rulechapter_customuser_school_class_ruledimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
