# Generated by Django 5.2.1 on 2025-05-17 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_description_to_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teaching_classes',
            field=models.ManyToManyField(blank=True, help_text='Subject classes taught by this teaching teacher.', related_name='teaching_teachers', to='api.schoolclass'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'class_teacher'}, related_name='led_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_type',
            field=models.CharField(choices=[('home_class', 'Home Class'), ('subject_class', 'Subject Class')], default='home_class', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teaching_teacher', 'Teaching Teacher'), ('class_teacher', 'Class Teacher'), ('moral_education_supervisor', 'Moral Education Supervisor'), ('principal', 'Principal'), ('director', 'Director'), ('system_administrator', 'System Administrator')], default='student', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='The home class a student belongs to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.schoolclass'),
        ),
        migrations.CreateModel(
            name='StudentParentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student-Parent Relationship',
                'verbose_name_plural': 'Student-Parent Relationships',
                'unique_together': {('student', 'parent')},
            },
        ),
    ]
